Disable typescript analysis for now.
There's an issue with the way we're making a Program. The linter's integration tests are failing right now with this stack trace:

     TypeError: Cannot read property 'length' of null
      at fileExtensionIs (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:2829:20)
      at tryGetExtensionFromPath (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:3410:13)
      at Object.extensionFromPath (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:3402:19)
      at /Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:63897:46
      at Array.map (native)
      at resolveModuleNamesWorker (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:63891:141)
      at resolveModuleNamesReusingOldState (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:64075:24)
      at processImportedModules (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:64869:35)
      at findSourceFile (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:64779:17)
      at processSourceFile (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:64682:27)
      at processRootFile (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:64570:13)
      at /Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:63919:60
      at Object.forEach (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:1398:30)
      at Object.createProgram (/Users/rictic/open/analyzer/node_modules/typescript/lib/typescript.js:63919:16)
      at TypeScriptAnalyzer.analyze (/Users/rictic/open/analyzer/lib/typescript/typescript-analyzer.js:30:19)
      at AnalysisContext.getDocument (/Users/rictic/open/analyzer/lib/core/analysis-context.js:211:47)
      at scannedDocuments.map (/Users/rictic/open/analyzer/lib/core/analysis-context.js:162:68)
      at Array.map (native)
      at AnalysisContext.<anonymous> (/Users/rictic/open/analyzer/lib/core/analysis-context.js:162:52)
      at next (native)
      at fulfilled (/Users/rictic/open/analyzer/lib/core/analysis-context.js:17:58)

Since this feature isn't hooked up yet and 2.0's release is very imminent let's disable typescript whole-program analysis for the moment.